const data = [
  {
    id: 1,
    title: "Calculator with JavaScript",
    img: "calc.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/js-calculator",
    demo: "https://calculator-js-pro.netlify.app/",
    tags: "#vanilla.js",
  },
  {
    id: 2,
    title: "Personal Chat With JavaScript",
    img: "contact.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/JS-Chat",
    demo: "https://personal-chat-js.netlify.app",
    tags: "#vanilla.js",
  },
  {
    id: 3,
    title: "Weather Forecast Site with JavaScript",
    img: "weather.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/weather-forecast-js",
    demo: "https://weatherforecast-javascript.netlify.app/",
    tags: "#vanilla.js",
  },
  {
    id: 4,
    title: "Snow and Slider with JavaScript",
    img: "snow.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/slider-js",
    demo: "https://snow-slider.netlify.app/",
    tags: "#vanilla.js",
  },
  {
    id: 5,
    title: "Ecommerce  With React-Redux",
    img: "techno.png",
    type: "react",
    github: "https://github.com/ceyhunresulov/techno-react-redux",
    demo: "https://techno-react-redux.netlify.app/",
    tags: "#react  #redux  #tailwind",
  },
  {
    id: 6,
    title: "Wolt Clone",
    img: "wolt.png",
    type: "react",
    github: "https://github.com/ceyhunresulov/wolt",
    demo: "https://wolt-clone.netlify.app/",
    tags: "#react  #redux  #tailwind",
  },
  {
    id: 7,
    title: "Edinify (LMS)",
    img: "edinify.png",
    type: "private",
    desc: "Edinify is a Learning Management System (LMS) designed to streamline the management and organization of courses for educational institutions and training organizations.",
    github: "",
    demo: "https://www.edinify.com/",
    tags: "#real-project #full-stack #react  #redux #mui #node.js #express.js #mongodb ",
  },
  {
    id: 8,
    title: "Robitesk",
    img: "robitesk.jpg",
    desc: "Robitesk is Social Media & E-commerce & Online Courses. An app consisting of several modules designed for children. This app covers: social media, e-commerce and online courses.",
    type: "private",
    github: "",
    demo: "",
    tags: "#real-project #mern-stack #full-stack #react #redux #mui #node.js #express.js #mongodb #socket.io ",
  },
].sort((a, b) => b.id - a.id);

export default data;
