const data = [
  {
    id: 1,
    title: "Calculator with JavaScript",
    img: "calc.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/js-calculator",
    demo: "https://calculator-js-pro.netlify.app/",
    desc: "#vanilla.js",
  },
  {
    id: 2,
    title: "Personal Chat With JavaScript",
    img: "contact.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/JS-Chat",
    demo: "https://personal-chat-js.netlify.app",
    desc: "#vanilla.js",
  },
  {
    id: 3,
    title: "Weather Forecast Site with JavaScript",
    img: "weather.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/weather-forecast-js",
    demo: "https://weatherforecast-javascript.netlify.app/",
    desc: "#vanilla.js",
  },
  {
    id: 4,
    title: "Snow and Slider with JavaScript",
    img: "snow.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/slider-js",
    demo: "https://snow-slider.netlify.app/",
    desc: "#vanilla.js",
  },
  {
    id: 5,
    title: "Ecommerce  With React-Redux",
    img: "techno.png",
    type: "react",
    github: "https://github.com/ceyhunresulov/techno-react-redux",
    demo: "https://techno-react-redux.netlify.app/",
    desc: "#react  #redux  #tailwind",
  },
  {
    id: 6,
    title: "Wolt Clone",
    img: "wolt.png",
    type: "react",
    github: "https://github.com/ceyhunresulov/wolt",
    demo: "https://wolt-clone.netlify.app/",
    desc: "#react  #redux  #tailwind",
  },
  {
    id: 7,
    title: "Edinify (BMS)",
    img: "edinify.png",
    type: "private",
    github: "",
    demo: "https://www.edinify.com/",
    desc: "#real-project #full-stack #react  #redux #mui #node.js #express.js #mongodb ",
  },
].sort((a, b) => b.id - a.id);

export default data;
