const data = [
  {
    id: 1,
    title: "Calculator with JavaScript",
    img: "calc.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/js-calculator",
    demo: "https://calculator-js-pro.netlify.app/",
  },
  {
    id: 3,
    title: "Personal Chat With JavaScript",
    img: "contact.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/JS-Chat",
    demo: "https://personal-chat-js.netlify.app",
  },
  {
    id: 4,
    title: "Weather Forecast Site with JavaScript",
    img: "weather.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/weather-forecast-js",
    demo: "https://weatherforecast-javascript.netlify.app/",
  },
  {
    id: 5,
    title: "Random Color Background with JavaScript",
    img: "bg_color.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/bg-color-js",
    demo: "https://js-bg-color.netlify.app/",
  },
  {
    id: 6,
    title: "Snow and Slider with JavaScript",
    img: "snow.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/slider-js",
    demo: "https://snow-slider.netlify.app/",
  },
  {
    id: 7,
    title: "Todo List With React-Redux",
    img: "todoredux.png",
    type: "react",
    github: "https://github.com/ceyhunresulov/todo-react-redux",
    demo: "https://todolistwithreact-redux.netlify.app/",
  },
  {
    id: 8,
    title: "Currency Converter With React-Redux",
    img: "currency.png",
    type: "react",
    github: "https://github.com/ceyhunresulov/currency-converter",
    demo: "https://currencyconverter-react.netlify.app/",
  },
  {
    id: 9,
    title: "Ecommerce  With React-Redux",
    img: "techno.png",
    type: "react",
    github: "https://github.com/ceyhunresulov/techno-react-redux",
    demo: "https://techno-react-redux.netlify.app/",
  },
  {
    id: 10,
    title: "Tic Tac Toe  With JavaScript",
    img: "xo.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/x-o--js",
    demo: "https://x-o-js.netlify.app/",
  },
  {
    id: 11,
    title: "Search  With JavaScript",
    img: "search.png",
    type: "js",
    github: "https://github.com/ceyhunresulov/search-bar-js",
    demo: "https://searchbar-js.netlify.app/",
  },
].sort((a, b) => b.id - a.id);

export default data;
